### ISSUE TITLE
Using multiple shell inline provisioner is not possible

### ISSUE THREAD

**Issue by lee-pai-long** [lee-pai-long/vagabon#1]
- In vagrant.yml:

```yaml
provision:
  shell:
    inline: "echo 'shell inline example'"
```

the shell key should be a list.

- In Vagrantfile:

```ruby
if minion["provision"]["shell"].key?("inline")
  m.vm.provision "shell",
  inline: minion["provision"]["shell"]["inline"]
end
```

It should be a loop
